name: Deploy

on:
  workflow_dispatch:

jobs:
  placeholder:
    name: Placeholder
    runs-on: ubuntu-latest
    steps:
      - name: Explain status
        run: echo "Deployment workflow placeholder. Implementation pending."
